function Resolved = isresolved(X, Y, ell)
%ISRESOLVED check if a blob fit a given ellipse is resolved from others.
%
%Input arguments:
%   X and Y are coordinates variable matrices.
%   X and Y are generated by:
%   [X,Y] = meshgrid(1:NX, 1:NY), where NX and NY are number of points
%   along x-axis and y-axis.
%
%Return:
%   Resolved is a logical vector. 0 stands for unresolved while 1 stands for
%   resolved.
[NY, NX] = size(X);
[~,NumEll] = size(ell);
Resolved = false(1,NumEll);
rmax = max(ell(3,:));
for k = 1:NumEll
    % define the rectangular neighbourhood for the current ellipse
    xc = ell(1,k);
    yc = ell(2,k);
    xmin = floor(max(1,xc-rmax));
    xmax = ceil(min(xc+rmax,NX));
    ymin = floor(max(1,yc-rmax));
    ymax = ceil(min(yc+rmax,NY));
    % idx of neighbour ellipses
    nidx = find(ell(1,:) >= xmin & ell(1,:) <= xmax &...
        ell(2,:) >= ymin & ell(2,:) <= ymax & 1:NumEll ~= k);
    % area of neighbour ellipses
    narea = false(ymax-ymin+1,xmax-xmin+1);
    for l = 1:length(nidx)
        narea = narea | ellishade(X(ymin:ymax,xmin:xmax),...
            Y(ymin:ymax,xmin:xmax),...
            ell(:,nidx(l)));
    end
    % area of current ellipse
    carea = ellishade(X(ymin:ymax,xmin:xmax),...
        Y(ymin:ymax,xmin:xmax),ell(:,k));
    if ~any(carea & narea)
        Resolved(k) = true;
    end
end
return
