clear
close all
B = 10;
G = 100*fspecial('gauss',256,8);
x = 4;
y = 7;
P = fspecial('gauss',256,3);
A = 20;
Pxy = circshift(P,[y,x]);
O = A*Pxy;
I = normrnd(B+G+O,0.002);
[g,m,~,r] = srcsprtmtv(sdwt2(I,1),sdwt2(Pxy,1),20,[],100,100);
% figure('Name','Original image')
% imagesc(I)
% imprint('x','x, pixel',...
%   'y','y, pixel',...
%   'title','Original image',...
%   'c','intensity',...
%   'cmap','hot',...
%   'fontsize',16,'picname','origimage','format','bitmap')
% [Atv,TV] = findampmtv(I,P,x,y);
% xrng = -10:10;
% yrng = -10:10;
% [~,xmtv,ymtv,~,TVmap] = findposmtv(I,P,xrng,yrng);
% figure('Name','TV map, pass 1');
% imagesc(xrng,yrng,TVmap)
% imprint('x','x, pixel',...
%   'y','y, pixel',...
%   'title','TV map, pass 1',...
%   'c','TV',...
%   'cmap','hot',...
%   'fontsize',16,'picname','tvmap-pass1','format','bitmap')
% xrng = xmtv+(-2:0.2:2);
% yrng = ymtv+(-2:0.2:2);
% [Amtv,xmtv,ymtv,~,TVmap] = findposmtv(I,P,xrng,yrng);
% figure('Name','TV map, pass 2');
% imagesc(xrng,yrng,TVmap)
% imprint('x','x, pixel',...
%   'y','y, pixel',...
%   'title','TV map, pass 2',...
%   'c','TV',...
%   'cmap','hot',...
%   'fontsize',16,'picname','tvmap-pass2','format','bitmap')
% Pmtv = subshift(P,[ymtv,xmtv]);
% Gmtv = I - Pmtv*Amtv + B;
% figure('Name','Separated galaxy image')
% imagesc(Gmtv)
% imprint('x','x, pixel',...
%   'y','y, pixel',...
%   'title','Separated galaxy image',...
%   'c','intensity',...
%   'cmap','hot',...
%   'fontsize',16,'picname','galaxyimage','format','bitmap')
% figure('Name','Error')
% imagesc(G - Gmtv)
% imprint('x','x, pixel',...
%   'y','y, pixel',...
%   'title','Separation error',...
%   'c','intensity',...
%   'cmap','hot',...
%   'fontsize',16,'picname','sprterror','format','bitmap')
% imagesc(Pmtv*Amtv)
% imprint('x','x, pixel',...
%   'y','y, pixel',...
%   'title','Separated point source',...
%   'c','intensity',...
%   'cmap','hot',...
%   'fontsize',16,'picname','sprtpts','format','bitmap')
