function S = ellishade(X, Y, ell)
%ELLISHADE elliptical shading
%
%Input arguments:
%   X and Y are coordinates variable matrices.
%   X and Y are generated by:
%   [X,Y] = meshgrid(1:NX, 1:NY), where NX and NY are number of points
%   along x-axis and y-axis.
[~,NumEll] = size(ell);
S = false(size(X));
for k = 1:NumEll
    y = Y - ell(2,k);
    x = X - ell(1,k);
    phi = atan2(y,x) - ell(5,k);
    rho2 = x.^2 + y.^2;
    S = S | ...
        (rho2 <= ...
        ((ell(3,k)*ell(4,k))^2)./...
        ((ell(3,k)*sin(phi)).^2 + (ell(4,k)*cos(phi)).^2));
end
return
